name: haptica
description: Інтелектуальна система перетворення жестової мови на базі смарт-рукавички
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI пакети
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.7
  lottie: ^2.6.0
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.0
  flutter_native_splash: ^2.3.1
  speech_to_text: ^6.3.0

  # Архітектура і управління станом
  provider: ^6.0.5
  get_it: ^7.6.0
  dartz: ^0.10.1

  flutter_blue_plus: ^1.14.1
  permission_handler: ^10.4.3

  # База даних
  sqflite: ^2.3.0
  path_provider: ^2.1.0
  shared_preferences: ^2.2.0

  # Машинне навчання
  # tflite_flutter: ^0.9.0
  # Тимчасово відключаємо ML для вирішення проблем збірки

  # Інструменти
  intl: ^0.19.0
  logger: ^1.4.0
  uuid: ^3.0.7
  equatable: ^2.0.5

  # Firebase
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  google_sign_in: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.4.6
  mockito: ^5.4.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/ml/
    - assets/images/google_logo.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700

# Налаштування Splash Screen
flutter_native_splash:
  color: "#FFD700"  # Жовтий колір (Ваш AppTheme.primaryColor)
  image: assets/images/logo.png  # Шлях до логотипу (потрібно створити або використати існуючий)
  color_dark: "#121212"  # Темний фон для темної теми
  image_dark: assets/images/logo.png  # Той самий або інший логотип для темної теми

  android: true
  ios: true
  web: false

  android_12:
    image: assets/images/logo.png
    icon_background_color: "#FFD700"
    image_dark: assets/images/logo.png
    icon_background_color_dark: "#121212"